"""
Summary Generator Module
Generates one-liner summaries using layered approach:
1. Local LLM (Ollama) - preferred
2. Cloud API (Moonshot/Bailian) - optional
3. Heuristic extraction - fallback
"""

import os
import json
from typing import Optional, Dict, Any
from pathlib import Path

from core.logger import get_logger

logger = get_logger(__name__)


class SummaryGenerator:
    """Generate one-liner summaries for meeting audio"""
    
    def __init__(self, method: str = "auto"):
        """
        Initialize summary generator
        
        Args:
            method: Summary method (auto|llm|cloud|heuristic|none)
        """
        self.method = method
        self.ollama_url = os.getenv("OLLAMA_HOST", "http://localhost:11434")
        self.ollama_model = os.getenv("OLLAMA_MODEL", "qwen2.5:7b")
        self.cloud_provider = os.getenv("SUMMARY_CLOUD_PROVIDER", "")
        self.cloud_api_key = os.getenv("SUMMARY_CLOUD_API_KEY", "")
        
    def generate(self, transcript: str, context: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Generate summary using layered approach
        
        Args:
            transcript: Full or partial transcript text
            context: Additional context (speakers, duration, etc.)
            
        Returns:
            Summary dict with one_liner, method, confidence, etc.
        """
        if self.method == "none":
            return self._no_summary()
        
        # Try LLM first (if auto or llm)
        if self.method in ["auto", "llm"]:
            result = self._try_llm(transcript, context)
            if result and result.get("one_liner"):
                return result
        
        # Try cloud API (if auto or cloud)
        if self.method in ["auto", "cloud"]:
            result = self._try_cloud(transcript, context)
            if result and result.get("one_liner"):
                return result
        
        # Fallback to heuristic
        if self.method in ["auto", "heuristic"]:
            return self._try_heuristic(transcript, context)
        
        return self._no_summary()
    
    def _try_llm(self, transcript: str, context: Dict[str, Any] = None) -> Optional[Dict[str, Any]]:
        """Try local LLM (Ollama)"""
        try:
            import requests
            
            # Truncate transcript to avoid token limits
            truncated = transcript[:2000] if len(transcript) > 2000 else transcript
            
            prompt = f"请用一句话总结这个会议内容，不超过 50 字：\n\n{truncated}"
            
            response = requests.post(
                f"{self.ollama_url}/api/generate",
                json={
                    "model": self.ollama_model,
                    "prompt": prompt,
                    "stream": False
                },
                timeout=30
            )
            
            if response.status_code == 200:
                result = response.json()
                one_liner = result.get("response", "").strip()
                
                if one_liner:
                    logger.info("Summary generated by local LLM")
                    return {
                        "one_liner": one_liner,
                        "method": "llm",
                        "model": self.ollama_model,
                        "confidence": 0.85
                    }
            
            logger.warning("Local LLM failed, trying fallback")
            
        except Exception as e:
            logger.debug(f"LLM summary failed: {e}")
        
        return None
    
    def _try_cloud(self, transcript: str, context: Dict[str, Any] = None) -> Optional[Dict[str, Any]]:
        """Try cloud API (Moonshot/Bailian)"""
        if not self.cloud_api_key:
            return None
        
        try:
            # Moonshot API example
            if self.cloud_provider == "moonshot":
                import requests
                
                truncated = transcript[:2000] if len(transcript) > 2000 else transcript
                
                response = requests.post(
                    "https://api.moonshot.cn/v1/chat/completions",
                    headers={
                        "Authorization": f"Bearer {self.cloud_api_key}",
                        "Content-Type": "application/json"
                    },
                    json={
                        "model": "moonshot-v1-8k",
                        "messages": [
                            {"role": "system", "content": "你是一个会议摘要助手，用一句话总结会议内容。"},
                            {"role": "user", "content": f"请总结这个会议：{truncated}"}
                        ],
                        "max_tokens": 100
                    },
                    timeout=10
                )
                
                if response.status_code == 200:
                    result = response.json()
                    one_liner = result["choices"][0]["message"]["content"].strip()
                    
                    logger.info("Summary generated by cloud API")
                    return {
                        "one_liner": one_liner,
                        "method": "cloud",
                        "provider": self.cloud_provider,
                        "confidence": 0.90
                    }
            
        except Exception as e:
            logger.debug(f"Cloud summary failed: {e}")
        
        return None
    
    def _try_heuristic(self, transcript: str, context: Dict[str, Any] = None) -> Dict[str, Any]:
        """Heuristic extraction - keyword-based"""
        # Extract key phrases
        key_phrases = self._extract_key_phrases(transcript)
        
        # Build summary from keywords
        if key_phrases:
            one_liner = f"会议讨论：{', '.join(key_phrases[:5])}"
        else:
            one_liner = "会议录音分析完成"
        
        logger.info("Summary generated by heuristic method")
        return {
            "one_liner": one_liner,
            "method": "heuristic",
            "confidence": 0.50,
            "key_topics": key_phrases[:5]
        }
    
    def _extract_key_phrases(self, transcript: str) -> list:
        """Extract key phrases using simple frequency analysis"""
        # Common Chinese meeting words to look for
        meeting_keywords = [
            "周报", "日报", "月报", "项目", "进度", "计划", "安排",
            "人员", "团队", "开发", "测试", "产品", "设计",
            "会议", "讨论", "决定", "需要", "完成", "今天", "明天", "下周"
        ]
        
        # Count occurrences
        keyword_counts = {}
        for kw in meeting_keywords:
            count = transcript.count(kw)
            if count > 0:
                keyword_counts[kw] = count
        
        # Sort by frequency
        sorted_keywords = sorted(keyword_counts.items(), key=lambda x: x[1], reverse=True)
        
        return [kw for kw, count in sorted_keywords[:10]]
    
    def _no_summary(self) -> Dict[str, Any]:
        """Return empty summary"""
        return {
            "one_liner": "",
            "method": "none",
            "confidence": 0.0,
            "note": "Summary generation disabled"
        }
